
controllers:
  - turtlebot:
      name: turtlebot
      critical: true
      inputs:
        - frontSensor:
            name: frontSensor
            type: Integer
            default: 3
      outputs:
        - motorLeft:
            name: motorLeft
            type: Double
            default: 0.0
        - motorRight:
            name: motorRight
            type: Double
            default: 0.0

  - target:
      name: target
      critical: true
      inputs:
        - xcoordinate:
            name: xcoordinate
            type: Double
            default: 9999
        - ycoordinate:
            name: ycoordinate
            type: Double
            default: 9999
        - width:
            name: width
            type: Double
            default: 9999

