
controllers:
  - turtlebot:
      name: turtlebot
      critical: true
      inputs:
        - sensorFrontOne:
            name: sensorFrontOne
            type: Double
            default: -1.0
        - sensorFrontTwo:
            name: sensorFrontTwo
            type: Double
            default: -1.0
        - sensorBackRight:
            name: sensorBackRight
            type: Double
            default: -1.0
        - sensorFrontRight:
            name: sensorFrontRight
            type: Double
            default: -1.0
        - sensorBackLeft:
            name: sensorBackLeft
            type: Double
            default: -1.0
        - sensorFrontLeft:
            name: sensorFrontLeft
            type: Double
            default: -1.0
        - sensorFrontOneDetect:
            name: sensorFrontOneDetect
            type: Integer
            default: -1
        - sensorFrontTwoDetect:
            name: sensorFrontTwoDetect
            type: Integer
            default: -1
        - sensorBackRightDetect:
            name: sensorBackRightDetect
            type: Integer
            default: -1
        - sensorFrontRightDetect:
            name: sensorFrontRightDetect
            type: Integer
            default: -1
        - sensorBackLeftDetect:
            name: sensorBackLeftDetect
            type: Integer
            default: -1
        - sensorFrontLeftDetect:
            name: sensorFrontLeftDetect
            type: Integer
            default: -1
        - xCoor:
            name: xCoor
            type: Double
            default: -1.0
        - yCoor:
            name: yCoor
            type: Double
            default: -1.0
        - zRot:
            name: zRot
            type: Double
            default: -1.0
      outputs:
        - motorLeft:
            name: motorLeft
            type: Double
            default: 0.0
        - motorRight:
            name: motorRight
            type: Double
            default: 0.0

  - target:
      name: target
      critical: true
      inputs:
        - xCoorTarget:
            name: xCoorTarget
            type: Double
            default: -1
        - yCoorTarget:
            name: yCoorTarget
            type: Double
            default: -1
        - width:
            name: width
            type: Double
            default: -1
    
  - controller:
      name: controller
      critical: true
      inputs:
        - yJoystick:
            name: yJoystick
            type: Double
            default: -1
        - xJoystick:
            name: xJoystick
            type: Double
            default: -1

